# from common.code import Code


class Code:

	REC_METHOD_VOICE_CHAT = "voice-chat"
	REC_METHOD_VOICE_EXEC = "execute-command"

	REC_ACTION_SLEEP_ASSISTANT = "sleep_assistant"

	REC_ACTION_COMMAND = "cmd"

	REC_ACTION_PARAMS_DEVICE_VOLUME = "volume"
	REC_ACTION_PARAMS_DEVICE_LIGHT = "light"
	REC_ACTION_PARAMS_DEVICE_FRAGRANCE = "fragment"
	REC_ACTION_PARAMS_DEVICE_SYSTEM = "system"

	REC_ACTION_PARAMS_OPER_SOUND_MAIN = "main"
	REC_ACTION_PARAMS_OPER_VOICE = "voice"
	REC_ACTION_PARAMS_OPER_BACKSOUND = "background_sound"
	REC_ACTION_PARAMS_OPER_MUSIC = "music"

	REC_ACTION_PARAMS_OPER_BRIGHTNESS = "brightness"
	REC_ACTION_PARAMS_OPER_COLOR = "color"
	REC_ACTION_PARAMS_OPER_MODE = "mode"
	REC_ACTION_PARAMS_OPER_STATE = "STATE"

	REC_ACTION_PARAMS_OPER_FRAGRANCE = "fragrance"

	REC_ACTION_PARAMS_OPER_SYSTEM = "system"

	REC_ACTION_PARAMS_VALUE_UP = "up"
	REC_ACTION_PARAMS_VALUE_DOWN = "down"
	REC_ACTION_PARAMS_VALUE_ON = "on"
	REC_ACTION_PARAMS_VALUE_OFF = "off"

	REC_ACTION_PARAMS_VALUE_GREEN = "green"
	REC_ACTION_PARAMS_VALUE_RED = "red"
	REC_ACTION_PARAMS_VALUE_BLUE = "blue"
	REC_ACTION_PARAMS_VALUE_YELLOW = "yellow"
	REC_ACTION_PARAMS_VALUE_PURPLE = "purple"
	REC_ACTION_PARAMS_VALUE_WHITE = "white"

	REC_ACTION_PARAMS_VALUE_SLEEP = "sleep"

	EXECUTE_COMMAND_TIP_VOICE = "execute-command-tip-voice"

	LIGHT_MODE_GRADIENT = "Gradient"
	LIGHT_MODE_BREATHING = "Breathing"
	LIGHT_MODE_CIRCLE = "Circle"
	LIGHT_MODE_CIRCLE_RAINBOW = "CircleRainbow"
	LIGHT_MODE_SECTOR_FLOWING = "SectorFlowing"
	LIGHT_MODE_RANDOM_POINT = "RandomPoint"
	LIGHT_MODE_STATIC = "Static"
	LIGHT_MODE_WAVE = "Wave"

	LIGHT_TYPE_SET = "set"
	LIGHT_TYPE_TEMP = "temp"
	LIGHT_TYPE_DIY = "diy"

	@staticmethod
	def lightModelMap():
		return {
			"Gradient": Code.LIGHT_MODE_BREATHING,
			"Static": Code.LIGHT_MODE_GRADIENT,
			"Circle": Code.LIGHT_MODE_CIRCLE,
			"CircleRainbow": Code.LIGHT_MODE_CIRCLE_RAINBOW,
			"SectorFlowing": Code.LIGHT_MODE_SECTOR_FLOWING,
			"RandomPoint": Code.LIGHT_MODE_RANDOM_POINT,
			"Wave": Code.LIGHT_MODE_WAVE,
		}
		
